<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>LoadoutPresets</AssemblyName>
    <Description>Template Mod</Description>
    <Version>0.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	  <RootNamespace>LoadoutPresets</RootNamespace>
    
    <!-- Set your R2ModMan profile path here -->
    <R2ModManProfile>C:\Users\grube\AppData\Roaming\r2modmanPlus-local\Megabonk\profiles\Mods\BepInEx\plugins\ZeusesNeckMeat-LoadoutPresets</R2ModManProfile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" Publicize="true">
      <HintPath>Libs\Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>Libs\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>Libs\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>Libs\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>Libs\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>Libs\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>Libs\Il2CppSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>Libs\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Libs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>Libs\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>Libs\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>Libs\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Post-build event to copy DLL to R2ModMan profile -->
  <Target Name="CopyToR2ModMan" AfterTargets="Build" Condition="Exists('$(R2ModManProfile)')">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(R2ModManProfile)" />
    <Message Text="Copied $(TargetFileName) to R2ModMan profile" Importance="high" />
  </Target>
</Project>
